# Generated by Django 3.1 on 2021-08-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='cover_img_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
