# Generated by Django 3.1 on 2021-09-05 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20210830_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examsolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note')),
            ],
        ),
    ]
