# Generated by Django 3.1 on 2021-09-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_examsolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter',
            field=models.TextField(blank=True),
        ),
    ]
