# Generated by Django 3.1 on 2021-09-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20210906_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
